-- AlterTable
ALTER TABLE `Ledger` ADD COLUMN `barangGerobak` DOUBLE NULL DEFAULT 0,
    ADD COLUMN `barangKeluar` DOUBLE NULL DEFAULT 0,
    ADD COLUMN `bonus` DOUBLE NULL DEFAULT 0,
    ADD COLUMN `bop` DOUBLE NULL DEFAULT 0,
    ADD COLUMN `laba` DOUBLE NULL DEFAULT 0,
    ADD COLUMN `netIncome` DOUBLE NULL DEFAULT 0,
    ADD COLUMN `percentage` DOUBLE NULL DEFAULT 0,
    ADD COLUMN `session` INTEGER NULL DEFAULT 1,
    ADD COLUMN `sewaArmada` DOUBLE NULL DEFAULT 0,
    ADD COLUMN `sewaBarang` DOUBLE NULL DEFAULT 0,
    ADD COLUMN `sewaMobil` DOUBLE NULL DEFAULT 0;
